// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6iclWmGEzt-yvGd8zS0J3UYbRoI1YeM',
    appId: '1:234594820973:web:eaf6ba2dd44f8567137064',
    messagingSenderId: '234594820973',
    projectId: 'minerador-byt',
    authDomain: 'minerador-byt.firebaseapp.com',
    databaseURL: 'https://minerador-byt-default-rtdb.firebaseio.com',
    storageBucket: 'minerador-byt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEfkJ-Wo_OjkEsLnNoKAkdhXiilQ1kh8s',
    appId: '1:234594820973:android:57303cb773387f32137064',
    messagingSenderId: '234594820973',
    projectId: 'minerador-byt',
    databaseURL: 'https://minerador-byt-default-rtdb.firebaseio.com',
    storageBucket: 'minerador-byt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfS7fb_FadM308xNSl0FG_k1IGhPNonsU',
    appId: '1:234594820973:ios:d156e0b24dea9add137064',
    messagingSenderId: '234594820973',
    projectId: 'minerador-byt',
    databaseURL: 'https://minerador-byt-default-rtdb.firebaseio.com',
    storageBucket: 'minerador-byt.firebasestorage.app',
    iosClientId:
        '234594820973-13a1e61837tuvm968s5rh61e0plq7vch.apps.googleusercontent.com',
    iosBundleId: 'com.example.emporioGoldAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfS7fb_FadM308xNSl0FG_k1IGhPNonsU',
    appId: '1:234594820973:ios:d156e0b24dea9add137064',
    messagingSenderId: '234594820973',
    projectId: 'minerador-byt',
    databaseURL: 'https://minerador-byt-default-rtdb.firebaseio.com',
    storageBucket: 'minerador-byt.firebasestorage.app',
    iosClientId:
        '234594820973-13a1e61837tuvm968s5rh61e0plq7vch.apps.googleusercontent.com',
    iosBundleId: 'com.example.emporioGoldAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa6iclWmGEzt-yvGd8zS0J3UYbRoI1YeM',
    appId: '1:234594820973:web:9e33cee2394312b4137064',
    messagingSenderId: '234594820973',
    projectId: 'minerador-byt',
    authDomain: 'minerador-byt.firebaseapp.com',
    databaseURL: 'https://minerador-byt-default-rtdb.firebaseio.com',
    storageBucket: 'minerador-byt.firebasestorage.app',
  );
}
